[package]
name = "safe-chain-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rama = { git = "https://github.com/plabayo/rama", features = ["http-full", "dns", "rustls"] }
tokio = { version = "1.48.0", features = ["full"] }
